### PR TITLE
Adding Jacksonville, FL

### PR DESCRIPTION
**Pull request by carlvlewis**
Trying to follow alphabetic order.

### CODE REVIEW

**Comment by alan707** [comment]
Carl,
I've been trying to find the discretionary threshold for JAX and couldn't find the limit or the URL.  Have been looking for a while here: https://www.municode.com/library/fl/jacksonville/codes/code_of_ordinances

**Comment by carlvlewis** [comment]
I included the URL. Hang on.

---

i = 'carlvlewis'
i[dot]net
@i
github[dot]com/i

---

"Technology is neither good nor bad; nor is it neutral." -Melvin Kransberg

On Sat, Oct 17, 2015 at 10:52 AM -0700, "Alan Mond" notifications@github.com wrote:

Carl,

I've been trying to find the discretionary threshold for JAX and couldn't find the limit or the URL.  Have been looking for a while here: https://www.municode.com/library/fl/jacksonville/codes/code_of_ordinances

**Comment by alan707** [comment]
I think the URL you included does not talk about the discretionary limit.  That is why I dove deep into the MuniCode library...

**Comment by carlvlewis** [comment]
http://www.coj.net/departments/central-operations/procurement/bidding-opportunities-(including-capital-improveme.aspx

-- 
Carl V. Lewis
Sent with Airmail

**Comment by alan707** [comment]
I'll merge your PR and we can add it later if we find it :)

**Comment by carlvlewis** [comment]
This is a clearer definition on a different page:http://www.coj.net/departments/intra-governmental-services/procurement/doing-business-with-the-city.aspx

-- 
Carl V. Lewis
Sent with Airmail

On October 17, 2015 at 1:55:47 PM, Alan Mond (notifications@github.com) wrote:

Merged #34.

**Comment by alan707** [comment]
that's helpful.  I found the link for the discretionary spending: http://www.coj.net/departments/central-operations/docs/procurement/procurement-manual-revised-8-2-13(3).aspx#page=7

**Pull request merged**
